Repository FIWARE/helm-charts, pull requests merged in 2023-09, with the labels that each got.

#198 Fix ingress
  charts/api-umbrella/README.md
  charts/apollo/README.md
  charts/bae-activation-service/README.md
  charts/business-api-ecosystem/README.md
  charts/canis-major/README.md
  charts/credentials-config-service/README.md
  charts/dsba-pdp/README.md
  charts/endpoint-auth-service/README.md
  charts/iotagent-json/README.md
  charts/iotagent-ul/README.md
  charts/ishare-satellite/README.md
  charts/keyrock/README.md
  charts/mintaka/README.md
  charts/orion/README.md
  charts/scorpio-broker-aaio/README.md
  charts/scorpio-broker/README.md
  charts/tm-forum-api/Chart.yaml
  charts/tm-forum-api/README.md
  charts/tm-forum-api/templates/ingress.yaml
  charts/tm-forum-api/values.yaml
  charts/trusted-issuers-list/README.md
  charts/trusted-issuers-registry/README.md
Labels: patch

#199 Update README.md
  .github/workflows/deploy.yml
  README.md
Labels: patch

#200 Fix release
  .github/workflows/deploy.yml
Labels: patch

#201 Add api proxy
  charts/tm-forum-api/Chart.yaml
  charts/tm-forum-api/README.md
  charts/tm-forum-api/templates/envoy-configmap.yaml
  charts/tm-forum-api/templates/envoy-service.yaml
  charts/tm-forum-api/templates/envoy.yaml
  charts/tm-forum-api/values.yaml
Labels: minor

#202 Fix release
  charts/tm-forum-api/Chart.yaml
  charts/tm-forum-api/README.md
  charts/tm-forum-api/templates/envoy-service.yaml
Labels: patch

#203 Fix release
  charts/tm-forum-api/Chart.yaml
  charts/tm-forum-api/README.md
  charts/tm-forum-api/templates/envoy-service.yaml
Labels: patch

#204 Fix release
  charts/trusted-issuers-list/Chart.yaml
  charts/trusted-issuers-list/README.md
  charts/trusted-issuers-list/templates/_helpers.tpl
Labels: patch

#205 Fix release
  charts/trusted-issuers-list/Chart.yaml
  charts/trusted-issuers-list/README.md
  charts/trusted-issuers-list/templates/_helpers.tpl
Labels: patch

#206 contract management
  charts/contract-management/Chart.yaml
  charts/contract-management/README.md
  charts/contract-management/templates/_helpers.tpl
  charts/contract-management/templates/configmap.yaml
  charts/contract-management/templates/deployment.yaml
  charts/contract-management/templates/service.yaml
  charts/contract-management/templates/serviceaccount.yaml
  charts/contract-management/values.yaml
Labels: minor

#207 TIl service name override
  charts/trusted-issuers-list/Chart.yaml
  charts/trusted-issuers-list/README.md
  charts/trusted-issuers-list/templates/_helpers.tpl
  charts/trusted-issuers-list/templates/route-til.yaml
  charts/trusted-issuers-list/templates/route-tir.yaml
  charts/trusted-issuers-list/templates/service.yaml
  charts/trusted-issuers-list/values.yaml
Labels: deployment, minor

#208 TIL Init hook using generated service name
  charts/trusted-issuers-list/templates/post-hook-initdata.yaml
Labels: patch

#209 Pulledtim patch 1
  charts/trusted-issuers-list/Chart.yaml
  charts/trusted-issuers-list/README.md
Labels: patch
