Repository FIWARE/helm-charts, pull requests merged in 2025-08, with the labels that each got.

#365 fix defaults
  charts/business-api-ecosystem/Chart.yaml
  charts/business-api-ecosystem/README.md
  charts/business-api-ecosystem/values.yaml
Labels: patch

#367 Update values.yaml
  charts/trusted-issuers-list/Chart.yaml
  charts/trusted-issuers-list/README.md
  charts/trusted-issuers-list/values.yaml
Labels: patch

#368 Update values.yaml
  charts/vcverifier/Chart.yaml
  charts/vcverifier/values.yaml
Labels: minor

#369 Update values.yaml
  charts/trusted-issuers-list/Chart.yaml
  charts/trusted-issuers-list/README.md
  charts/trusted-issuers-list/values.yaml
Labels: minor

#370 Wistefan patch 1
  charts/contract-management/Chart.yaml
  charts/contract-management/README.md
  charts/contract-management/values.yaml
Labels: major

#371 Update values.yaml
  charts/vcverifier/Chart.yaml
  charts/vcverifier/values.yaml
Labels: patch

#373 Update values.yaml
  charts/contract-management/Chart.yaml
  charts/contract-management/README.md
  charts/contract-management/values.yaml
Labels: patch

#374 Replace image repos for bitnami
  charts/business-api-ecosystem/Chart.yaml
  charts/business-api-ecosystem/README.md
  charts/business-api-ecosystem/values.yaml
  charts/tm-forum-api/Chart.yaml
  charts/tm-forum-api/README.md
  charts/tm-forum-api/values.yaml
Labels: patch

#377 Update to latest PAP version
  charts/odrl-pap/Chart.yaml
  charts/odrl-pap/README.md
  charts/odrl-pap/values.yaml
Labels: major

#378 fix indention
  charts/odrl-pap/Chart.yaml
  charts/odrl-pap/README.md
  charts/odrl-pap/templates/deployment.yaml
Labels: patch

#381 Update values.yaml
  charts/trusted-issuers-list/Chart.yaml
  charts/trusted-issuers-list/README.md
  charts/trusted-issuers-list/values.yaml
Labels: patch

#383 feat(business-api-ecosystem): allow configuring the key of the password field for connecting to mongo
  charts/business-api-ecosystem/templates/biz-ecosystem-charging-backend/deployment.yaml
  charts/business-api-ecosystem/values.yaml
Labels: patch

#384 Update Base image
  charts/business-api-ecosystem/README.md
  charts/tm-forum-api/Chart.yaml
  charts/tm-forum-api/README.md
  charts/tm-forum-api/values.yaml
Labels: patch
