Repository FIWARE/helm-charts, pull requests merged in 2025-01, with the labels that each got.

#301 Update values.yaml
  charts/tm-forum-api/Chart.yaml
  charts/tm-forum-api/README.md
  charts/tm-forum-api/values.yaml
Labels: patch

#303 add chart
  charts/dss-validation-service/Chart.yaml
  charts/dss-validation-service/README.md
  charts/dss-validation-service/templates/_helpers.tpl
  charts/dss-validation-service/templates/deployment.yaml
  charts/dss-validation-service/templates/ingress.yaml
  charts/dss-validation-service/templates/secret.yaml
  charts/dss-validation-service/templates/service.yaml
  charts/dss-validation-service/templates/serviceaccount.yaml
  charts/dss-validation-service/templates/trustlist-config.yaml
  charts/dss-validation-service/values.yaml
Labels: patch

#304 Add dss validation
  charts/dss-validation-service/Chart.yaml
  charts/dss-validation-service/README.md
  charts/dss-validation-service/templates/keystore-secret.yaml
  charts/dss-validation-service/values.yaml
Labels: patch

#306 Add dss validation
  charts/dss-validation-service/Chart.yaml
  charts/dss-validation-service/README.md
  charts/dss-validation-service/templates/deployment.yaml
Labels: patch

#310 remove autoscaling ref
  charts/dss-validation-service/Chart.yaml
  charts/dss-validation-service/README.md
  charts/dss-validation-service/templates/deployment.yaml
Labels: patch

#312 change config
  charts/dss-validation-service/Chart.yaml
  charts/dss-validation-service/README.md
  charts/dss-validation-service/templates/deployment.yaml
Labels: patch

#313 Fix indention
  charts/dss-validation-service/Chart.yaml
  charts/dss-validation-service/README.md
  charts/dss-validation-service/templates/deployment.yaml
Labels: patch

#314 Another indention
  charts/dss-validation-service/Chart.yaml
  charts/dss-validation-service/README.md
  charts/dss-validation-service/templates/deployment.yaml
Labels: patch

#316 allow config overwrite
  charts/contract-management/Chart.yaml
  charts/contract-management/README.md
  charts/contract-management/templates/configmap.yaml
Labels: patch

#317 Update values.yaml
  charts/vcverifier/Chart.yaml
  charts/vcverifier/values.yaml
Labels: patch

#318 Update values.yaml
  charts/credentials-config-service/Chart.yaml
  charts/credentials-config-service/README.md
  charts/credentials-config-service/values.yaml
Labels: patch

#319 Add namespace to orion-ld deployment
  charts/orion/Chart.yaml
  charts/orion/README.md
  charts/orion/templates/deployment-hpa.yaml
  charts/orion/templates/deployment-mongo.yaml
  charts/orion/templates/deployment.yaml
  charts/orion/templates/ingress.yaml
  charts/orion/templates/initdata-cm.yaml
  charts/orion/templates/post-hook-initdata.yaml
  charts/orion/templates/route.yaml
  charts/orion/templates/secret.yaml
  charts/orion/templates/service-mongo.yaml
  charts/orion/templates/service.yaml
  charts/orion/templates/serviceaccount.yaml
  charts/orion/templates/test/orion-test.yaml
Labels: minor

#320 mintaka-ns from helm
  charts/mintaka/Chart.yaml
  charts/mintaka/README.md
  charts/mintaka/templates/deployment-hpa.yaml
  charts/mintaka/templates/deployment.yaml
  charts/mintaka/templates/ingress.yaml
  charts/mintaka/templates/route.yaml
  charts/mintaka/templates/secret.yaml
  charts/mintaka/templates/service.yaml
  charts/mintaka/templates/serviceaccount.yaml
Labels: minor

#321 Update values.yaml
  charts/vcverifier/Chart.yaml
  charts/vcverifier/values.yaml
Labels: patch

#322 Update values.yaml
  charts/odrl-pap/Chart.yaml
  charts/odrl-pap/README.md
  charts/odrl-pap/values.yaml
Labels: patch

#323 update to latest version
  charts/contract-management/Chart.yaml
  charts/contract-management/README.md
  charts/contract-management/templates/configmap.yaml
  charts/contract-management/templates/deployment.yaml
  charts/contract-management/values.yaml
Labels: major

#324 Update values.yaml
  charts/tm-forum-api/Chart.yaml
  charts/tm-forum-api/README.md
  charts/tm-forum-api/values.yaml
Labels: patch

#325 Update values.yaml
  charts/contract-management/Chart.yaml
  charts/contract-management/README.md
  charts/contract-management/values.yaml
Labels: patch

#326 Update values.yaml
  charts/tm-forum-api/Chart.yaml
  charts/tm-forum-api/README.md
  charts/tm-forum-api/values.yaml
Labels: patch
